### PR TITLE
fix: `totalSize` should be `paddingStart` + `paddingEnd` when size is 0

### PR DESCRIPTION
**Pull request by meowtec**

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This needs to be fixed up to remove the breaking changes that were rolled back. @piecyk, I'll leave that to you, or we can close this issue and fix it in `next`. You're call.

**Comment by meowtec** [comment]
@tannerlinsley has been rebased onto master

**Review by piecyk — APPROVED** [review]
Looks good, thanks 👍

**Pull request merged**
