### PR TITLE
feat: update project structure, migrate to typescript

### LINKED ISSUE #221: Migrate to typescript

### PR DESCRIPTION
**Pull request by piecyk**
closes #221

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This needs to be pointed at the `next` branch.

**Comment by tannerlinsley** [comment]
This is now pointed at the `next` branch. Probably needs a fixup, but I'll leave that up to you, @piecyk.

**Comment by piecyk** [comment]
Ok, thank 👍

**Comment by piecyk** [comment]
@tannerlinsley ready for review, maybe there is still some tweaks needed, based on https://github.com/TanStack/react-location

We can drop node10 support, and update github actions

**Pull request merged**
