### PR TITLE
fix: visible range isn't updated when measurements change

### LINKED ISSUE #112: Visible range isn't updated when measurements change
Hi 

noticed that when measurements change after initial render, visible range isn't updated. 
Range is updated on initial render, and next on every scroll.

Maybe let's add isScrolling on state and have an extra effect 

```tsx
useIsomorphicLayoutEffect(() => {
  if (!isScrolling && latestRef.current.scrollOffset !== undefined) {
    setRange(prevRange => calculateRange(latestRef.current, prevRange))
  }
}, [isScrolling, measurements])
```

### PR DESCRIPTION
**Pull request by piecyk**
closes #112

### CODE REVIEW

**Comment by piecyk** [comment]
@tannerlinsley 👋 once you have a moment, please take a look on this. Thanks.

About `isScrolling`... I know that it's adds an extra render after scroll, but having it included in lib would be more useful. We can document that in most cases user should add `pointerEvents: none` while scrolling for perfomance reasons. 

```jsx
<div
  ref={parentRef}
  style={{ height, width: '100%', overflow: 'auto', willChange: 'transform', position: 'relative' }}
>
  <div
    style={{
      height: `${rowVirtualizer.totalSize}px`,
      width: '100%',
      pointerEvents: isScrolling ? 'none' : 'auto',
    }}
  >
    {...}
  </div>
</div>
```

**Comment by piecyk** [comment]
Hi @tannerlinsley any updates on this? Sorry to ping you again 🙈  Maybe i can help and sort any question you have or add more tests 🤔 Would really love to get this released, as it's fixes few issues. Thanks 🙏

**Review by dariuszsobkowicz — APPROVED** [review]
lgtm

**Comment by piecyk** [comment]
Any news about this? 😉 Would be useful to have some time range when it will be review or what's it holding this back? 

Maybe other contributors also help resolve the issue 🙏

**Comment by piecyk** [comment]
Rebased with master, cc @tannerlinsley 😉 🙏 

Having `isScrolling` would allow in future to optimize overscan only in direction user is scrolling 👍

**Pull request closed without merging**
