### PR TITLE
fix: adjust scroll position when item size change only when scrolling backward

### LINKED ISSUE #188: Changing the size of partially visible items triggers list to scroll
According to this line https://github.com/tannerlinsley/react-virtual/blob/433d9663cedb7332d738a236199f9f7e76639039/src/index.js#L178

in case of changing the size of partially visible items (for example expanding) list is scrolling to save same position for partially visible item: https://codesandbox.io/s/react-virtual-resizeobserver-transition-forked-65sg7?file=/src/App.js

https://user-images.githubusercontent.com/17138959/129550951-60a11154-48a6-42cd-a9d6-ccf818ad9bef.mov

### PR DESCRIPTION
**Pull request by piecyk**
closes #188

### CODE REVIEW

**Comment by Karpengold** [comment]
Is there any updates regarding this PR? It solves issue about changing size of partially visible items and also provides usefull isScrolling param so it will be good to have it :)

**Comment by Karpengold** [comment]
@piecyk 
Also one thing, what do you thin, how this fix will work in this case: https://codesandbox.io/s/react-virtual-resizeobserver-transition-forked-65sg7?file=/src/App.js

I added button to toggle first item by click, will list scroll after this fix?

**Comment by piecyk** [comment]
> I added button to toggle first item by click, will list scroll after this fix?

hmm it should, don't fully understand "will list scroll after..."

**Comment by gabycperezdias** [comment]
@piecyk Is this already released? I am not seeing the "release" label on it and although It was closed on Nov 24, I am using the latest 2.10.4 and https://github.com/TanStack/react-virtual/issues/188 is not resolved...

**Comment by piecyk** [comment]
@gabycperezdias no, it wasn't. This scroll adjustment issue #188 it's bit tricky as mention in this pull it should only happen when scrolling backward.

**Pull request closed without merging**
